language: go
go: 1.4

services:
  - cassandra

before_install:
  - rm -r main

before_script:
  # peg
  - go get -u github.com/pointlander/peg
  - go get github.com/peterh/liner
  - cqlsh -f schema/schema_test.cql

script:
  - git reset --hard HEAD && main/build_mains.sh && rm -r main
  - ./build_verify.sh
  - go test -v ./...
