language: go
go:
  - 1.5
  - 1.6

env:
  - GO15VENDOREXPERIMENT=1

services:
  - cassandra

before_script:
  - go get -u golang.org/x/tools/cmd/goimports
  - cqlsh -f metric_metadata/cassandra/schema/schema_test.cql

script:
  - ./testing_support/script/verify-build
  - go test -v -timeout 1m ./...
